name: PHP 7.4 Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      database:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: moje_tajne_heslo
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, mysqli

      - name: Wait for MySQL to be ready
        run: dockerize -wait tcp://localhost:3306 -timeout 1m

      - name: Load MySQL schema and data
        run: mysql -h localhost -u root -proot test_db < ./_db/1_create_proc_schema_init_data.sql

      - name: Set env variables
        run: echo "::set-env name=DATABASE_HOST::database\n::set-env name=DATABASE_USER::root\n::set-env name=DATABASE_PASS::moje_tajne_heslo\n::set-env name=DATABASE_NAME::plavani"

      - name: Run PHPUnit
        run: phpunit
